mysql: mysql+pymysql://root:123456@127.0.0.1/med_data
# classicmodels data_copilot

ai:
  tries: 1
  wait: 100
  data_rows: 2

llm:
  model_provider: openai #qwen #openai
  model: deepseek-chat
  url: "https://api.deepseek.com/v1/"

# qwen1.5-72b-chat   qwen1.5-110b-chat
# qwen-turbo  qwen-plus   qwen-max   qwen-long
# https://dashscope.aliyun.com/

# glm-4
# https://open.bigmodel.cn


server_port: 8087
